# Generated by Django 5.1.3 on 2024-12-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamewinnerinfo',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamewinnerinfo',
            name='player',
        ),
        migrations.DeleteModel(
            name='GamePlayerInfo',
        ),
        migrations.DeleteModel(
            name='GameWinnerInfo',
        ),
    ]
