# Generated by Django 5.1.3 on 2024-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
