# Generated by Django 5.1.3 on 2024-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_business_pricing', '0002_alter_carbusinesspricing_로밍평균요금'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbusinesspricing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carbusinesspricing',
            name='로밍평균요금',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
