# Generated by Django 5.1.3 on 2024-12-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "player",
            },
        ),
    ]
