# Generated by Django 5.1.3 on 2024-12-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dice',
            name='game',
        ),
        migrations.RemoveField(
            model_name='dice',
            name='player',
        ),
    ]
