# Generated by Django 5.1.3 on 2024-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('player_number', models.IntegerField()),
                ('dice_values', models.CharField(max_length=255)),
                ('total_score', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'game_record',
            },
        ),
    ]
