# Generated by Django 5.1.3 on 2024-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("winnerId", models.IntegerField(blank=True, null=True)),
                ("loserId", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "game",
            },
        ),
    ]
