# Generated by Django 5.1.4 on 2024-12-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSoftware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'game_software',
            },
        ),
    ]
