# Generated by Django 5.1.4 on 2024-12-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSoftwareImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='game_software.gamesoftware')),
            ],
            options={
                'db_table': 'game_software_image',
            },
        ),
        migrations.CreateModel(
            name='GameSoftwarePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='game_software.gamesoftware')),
            ],
            options={
                'db_table': 'game_software_price',
            },
        ),
    ]
