# Generated by Django 5.1.3 on 2024-12-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fruit_name', models.CharField(max_length=255)),
                ('fruit_number', models.IntegerField()),
            ],
            options={
                'db_table': 'FruitMart',
            },
        ),
    ]
