# Generated by Django 5.1.3 on 2024-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_mart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerNickName', models.CharField(max_length=225)),
                ('buyNumber', models.IntegerField()),
                ('fruitType', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
