# Generated by Django 5.1.3 on 2024-12-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_mart', '0002_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_table',
        ),
    ]
