# Generated by Django 5.1.3 on 2024-12-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_mart', '0003_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerNickName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='fruitType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
